import {type Node, Position} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType } from '../../types';

export const AN_WHITE_24V_240LPM: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    origin: [0.5, 0.5],
    data: { 
        image: {url:"./AN_WHITE_24V_240LPM.jpg", width: 62, height: 25} as ImageDataType,
        technicalID: "AN_WHITE_24V_240LPM",
        name: "compData.AN_WHITE_24V_240LPM.name",
        description: "compData.AN_WHITE_24V_240LPM.descriptionShort",
        popover: {
            description: "compData.AN_WHITE_24V_240LPM.description",
        },
        showName: true,
        technicalVersion: 1,
        group: "led",
        rotation: 0,
        rotatable: true,
        borderWidth: 2,
        resizableX: true,
        physLengthStep: 0.016667,
        handles: [
        {
            hid: "24V_start",
            type: "source",
            x: 2.7,
            y: 21.5,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V pin",
            description: "24V supply input",
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "W_start",
            type: "source",
            x: 2.7,
            y: 4,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "W",
            name: "W pin",
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "24V_end",
            type: "source",
            x: 2.7,
            y: 21.5,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V pin",
            description: "24V supply input"
        } as HandleDataType,
        {
            hid: "W_end",
            type: "source",
            x: 2.7,
            y: 4,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "W", name: "W pin"
        } as HandleDataType,
        {
            hid: "24V_middle",
            type: "source",
            x: 0,
            y: 21.5,
            xalign: "start",
            yalign: "start",
            width: 12,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V pin",
            description: "24V supply input",
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        {
            hid: "W_middle",
            type: "source",
            x: 0,
            y: 4,
            xalign: "start",
            yalign: "start",
            width: 12,
            height: 5,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "W",
            name: "W pin",
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        ]
    } as ComponentDataType,
}