import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType, CompInputFieldDataType, CompInputFieldsBoxType} from '../../types';

export const DCDC_mini: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },

    data: { 
        image: {url:"./DCDC_mini.jpg", width: 57, height: 36} as ImageDataType,
        technicalID: "DCDC_mini",
        name: "compData.DCDC_mini.name",
        description: "compData.DCDC_mini.descriptionShort",
        popover: {
            description: "compData.DCDC_mini.description",
            buyLinks: [
            ]
        },
        technicalVersion: 1,
        group: "electronics",
        rotation: 0,
        borderWidth: 2,
        resizableX: false,
        rotatable: true,
        inputFieldsBox: {
                    x: 28.5,
                    y: 44,
                    borderType: "solid",
                    borderColor: "black",
                    borderLineWidth: 0,
                    borderRadius: "0%",
                    backgroundColor: "transparent",
                    rotate180only: true,
                } as CompInputFieldsBoxType,
                inputFields: [
                    {
                        technicalID: "source_voltage",
                        type: "number_input",
                        name: "Vout",
                        value: 5,
                        min: 1,
                        max: 17,
                        step: 0.1,
                        unit: "V",
                        fieldWidth: 70,
                        color: "black"
                    } as CompInputFieldDataType,
                ],
        handles: [
            {
                borderColor: "red",
                borderLineWidth: 1,
                borderRadius: "50%",
                borderType: "dashed",
                description: "Input positive (0-23 V)",
                functions: [
                    "suppl_in"
                ],
                height: 6,
                hid: "IN",
                name: "Input +",
                position: "left",
                postype: "centered",
                tolVmax: 40,
                tolVmin: 0,
                type: "source",
                Vout: 0,
                width: 6,
                x: 3,
                xalign: "start",
                y: 3,
                yalign: "start",
                prefferedLineWidth: 3,
                prefferedLineDirection: "left",
            } as HandleDataType,
            {
                borderColor: "black",
                borderLineWidth: 1,
                borderRadius: "50%",
                borderType: "dashed",
                description: "GND",
                functions: [
                    "gnd"
                ],
                height: 6,
                hid: "GND1",
                name: "GND",
                position: "left",
                postype: "centered",
                tolVmax: 0,
                tolVmin: 0,
                type: "source",
                Vout: 0,
                width: 6,
                x: 3,
                xalign: "start",
                y: 33,
                yalign: "start",
                prefferedLineWidth: 3,
                prefferedLineDirection: "left",
            } as HandleDataType,
            {
                borderColor: "red",
                borderLineWidth: 1,
                borderRadius: "50%",
                borderType: "dashed",
                description: "Adjustable output",
                functions: [
                    "suppl_out"
                ],
                height: 6,
                hid: "OUT",
                name: "Output +",
                position: "left",
                postype: "centered",
                tolVmax: 40,
                tolVmin: 0,
                type: "source",
                Vout: 5,
                width: 6,
                x: 53.5,
                xalign: "start",
                y: 3,
                yalign: "start",
                prefferedLineWidth: 3,
                prefferedLineDirection: "right",
            } as HandleDataType,
            {
                borderColor: "black",
                borderLineWidth: 1,
                borderRadius: "50%",
                borderType: "dashed",
                description: "GND",
                functions: [
                    "gnd"
                ],
                height: 3,
                hid: "GND2",
                name: "GND",
                position: "left",
                postype: "centered",
                tolVmax: 0,
                tolVmin: 0,
                type: "source",
                Vout: 0,
                width: 3,
                x: 53.5,
                xalign: "start",
                y: 33,
                yalign: "start",
                prefferedLineWidth: 3,
                prefferedLineDirection: "right",
            } as HandleDataType,           
        ]
    } as ComponentDataType,
}