import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType, CompInputFieldsBoxType} from '../../types';

export const Elko: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    origin: [0.5, 0.5],
    data: { 
        image: {url:"./Elko.jpg", width: 88, height: 26} as ImageDataType,
        technicalID: "Elko",
        name: "compData.Elko.name",
        description: "compData.Elko.descriptionShort",
        popover: {
            description: "compData.Elko.description",
        },
        technicalVersion: 1,
        group: "electronics",
        rotation: 0,
        borderWidth: 2,
        resizableX: false,
        rotatable: true,
        inputFieldsBox: {
            x: 65,
            y: 32,
            borderType: "transparent",
            borderColor: "black",
            borderLineWidth: 0,
            borderRadius: "0%",
            backgroundColor: "transparent",
            rotate180only: true,
        } as CompInputFieldsBoxType,
        selectFields: [
            {
            technicalID: "NominalValue",
            name: "C",
            displayName: false,
            selectedValue: 100,
            unit: "F",
            fieldWidth: 100,
            customImage: false,
            color: "black",
            options: [
                {"value": 1.0, "label": "1.0 uF"},
                {"value": 1.2, "label": "1.2 uF"},
                {"value": 1.5, "label": "1.5 uF"},
                {"value": 1.8, "label": "1.8 uF"},
                {"value": 2.2, "label": "2.2 uF"},
                {"value": 2.7, "label": "2.7 uF"},
                {"value": 3.3, "label": "3.3 uF"},
                {"value": 3.9, "label": "3.9 uF"},
                {"value": 4.7, "label": "4.7 uF"},
                {"value": 5.6, "label": "5.6 uF"},
                {"value": 6.8, "label": "6.8 uF"},
                {"value": 8.2, "label": "8.2 uF"},

                {"value": 10, "label": "10 uF"},
                {"value": 12, "label": "12 uF"},
                {"value": 15, "label": "15 uF"},
                {"value": 18, "label": "18 uF"},
                {"value": 22, "label": "22 uF"},
                {"value": 27, "label": "27 uF"},
                {"value": 33, "label": "33 uF"},
                {"value": 39, "label": "39 uF"},
                {"value": 47, "label": "47 uF"},
                {"value": 56, "label": "56 uF"},
                {"value": 68, "label": "68 uF"},
                {"value": 82, "label": "82 uF"},

                {"value": 100, "label": "100 uF"},
                {"value": 120, "label": "120 uF"},
                {"value": 150, "label": "150 uF"},
                {"value": 180, "label": "180 uF"},
                {"value": 220, "label": "220 uF"},
                {"value": 270, "label": "270 uF"},
                {"value": 330, "label": "330 uF"},
                {"value": 390, "label": "390 uF"},
                {"value": 470, "label": "470 uF"},
                {"value": 560, "label": "560 uF"},
                {"value": 680, "label": "680 uF"},
                {"value": 820, "label": "820 uF"},

                {"value": 1000, "label": "1.0 mF"},
                {"value": 1200, "label": "1.2 mF"},
                {"value": 1500, "label": "1.5 mF"},
                {"value": 1800, "label": "1.8 mF"},
                {"value": 2200, "label": "2.2 mF"},
                {"value": 2700, "label": "2.7 mF"},
                {"value": 3300, "label": "3.3 mF"},
                {"value": 3900, "label": "3.9 mF"},
                {"value": 4700, "label": "4.7 mF"},
                {"value": 5600, "label": "5.6 mF"},
                {"value": 6800, "label": "6.8 mF"},
                {"value": 8200, "label": "8.2 mF"}
            ],
            },
        ],
        handles: [
        {
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            borderType: "dotted",
            description: "Terminal +",
            functions: [
                "dig_in"
            ],
            height: 4,
            hid: "Plus",
            name: "Plus",
            position: "left",
            postype: "left",
            tolVmax: 250,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 10,
            x: 5.5,
            xalign: "start",
            y: 7.5,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            borderType: "dotted",
            description: "Terminal -",
            functions: [
                "dig_in"
            ],
            height: 4,
            hid: "Minus",
            name: "Minus",
            position: "left",
            postype: "left",
            tolVmax: 250,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 10,
            x: 23,
            xalign: "start",
            y: 19.5,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        ]
    } as ComponentDataType,
}