import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType } from '../../types';

export const ESP32_38P: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    data: { 
        name: "compData.ESP32_38P.name",
        description: "compData.ESP32_38P.descriptionShort",
        popover: {
            description: "compData.ESP32_38P.description",
        },
        technicalID: "ESP32_38P",
        technicalVersion: 1,
        group: "controller",
        image: {url:"./ESP32_38P.jpg", width: 119, height: 239} as ImageDataType,
        rotation: 0,
        resizableX: false,
        rotatable: true,
        borderWidth: 2,
        handles: [
            {
                "borderColor": "#8c8c8c",
                "borderLineWidth": 2,
                "borderRadius": "5%",
                "borderType": "dotted",
                "description": "USB (power and data)",
                "functions": [
                  "usb_full"
                ],
                "height": 30,
                "hid": "usb",
                "name": "USB",
                "position": "left",
                "postype": "bottom",
                "tolVmax": 5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 35,
                "x": 60,
                "xalign": "start",
                "y": 222,
                "yalign": "start"
              },
			  {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "3.3 V",
                "functions": [
                    "suppl_in",
                    "suppl_out"
                ],
                "height": 8,
                "hid": "3V3",
                "name": "3.3 V",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 3,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 18,
                "yalign": "start"
            },
              {
                "borderColor": "blue",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Reset input",
                "functions": [
                    "rst"
                ],
                "height": 8,
                "hid": "EN",
                "name": "Enable",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 28.5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In, Analog in",
                "functions": [
                    "dig_in",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO36",
                "name": "GPIO 36",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 39.5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In, Analog in",
                "functions": [
                    "dig_in",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO39",
                "name": "GPIO 39",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 51,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In, Analog in",
                "functions": [
                    "dig_in",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO34",
                "name": "GPIO 34",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 62,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In, Analog in",
                "functions": [
                    "dig_in",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO35",
                "name": "GPIO 35",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 73,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO32",
                "name": "GPIO 32",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 84,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO33",
                "name": "GPIO 33",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 95,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO25",
                "name": "GPIO 25",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 106,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO26",
                "name": "GPIO 26",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 116.5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO27",
                "name": "GPIO 27",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 126.5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO14",
                "name": "GPIO 14",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 137,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (be careful: boot fails if pulled high, strapping pin)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO12",
                "name": "GPIO 12",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 5.1,
                "xalign": "start",
                "y": 148,
                "yalign": "start"
            },
			{
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Ground",
                "functions": [
                    "gnd"
                ],
                "height": 8,
                "hid": "GND1",
                "name": "GND (1)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 159,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO13",
                "name": "GPIO 13",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 170,
                "yalign": "start"
            },
			{
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (Attention: do not use, used for SPI Flash!)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO9",
                "name": "GPIO 9",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 181,
                "yalign": "start"
            },
			{
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (Attention: do not use, used for SPI Flash!)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO10",
                "name": "GPIO 10",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 192,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (Attention: do not use, used for SPI Flash!)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO11",
                "name": "GPIO 11",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 203,
                "yalign": "start"
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "5V",
                "functions": [
                    "suppl_in",
                    "suppl_out"
                ],
                "height": 8,
                "hid": "5V",
                "name": "5V",
                "position": "left",
                "postype": "centered",
                "tolVmax": 5.5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 5,
                "width": 8,
                "x": 4,
                "xalign": "start",
                "y": 214,
                "yalign": "start"
            },
			{
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Ground",
                "functions": [
                    "gnd"
                ],
                "height": 8,
                "hid": "GND2",
                "name": "GND (2)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 8,
                "x": 114,
                "xalign": "start",
                "y": 18,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO23",
                "name": "GPIO 23",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113.7,
                "xalign": "start",
                "y": 28.5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO22",
                "name": "GPIO 22",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113.7,
                "xalign": "start",
                "y": 39.5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (be careful: used for USB!)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO1",
                "name": "GPIO 1",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113.7,
                "xalign": "start",
                "y": 51,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (be careful: used for USB!)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO3",
                "name": "GPIO 3",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113.7,
                "xalign": "start",
                "y": 62,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO21",
                "name": "GPIO 21",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113.5,
                "xalign": "start",
                "y": 73,
                "yalign": "start"
            },
			{
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Ground",
                "functions": [
                    "gnd"
                ],
                "height": 8,
                "hid": "GND3",
                "name": "GND (3)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 8,
                "x": 113,
                "xalign": "start",
                "y": 84,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO19",
                "name": "GPIO 19",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113.5,
                "xalign": "start",
                "y": 95,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO18",
                "name": "GPIO 18",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113.5,
                "xalign": "start",
                "y": 106.5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (outputs PWM signal at boot; be careful: strapping pin)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO5",
                "name": "GPIO 5",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113.5,
                "xalign": "start",
                "y": 116.5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO17",
                "name": "GPIO 17",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113.5,
                "xalign": "start",
                "y": 126.5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO16",
                "name": "GPIO 16",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113,
                "xalign": "start",
                "y": 137,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO4",
                "name": "GPIO 4",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113,
                "xalign": "start",
                "y": 148,
                "yalign": "start"
            },
			{
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (be crafeul: strapping pin, enters serial bootloader when pulled LOW during reset)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO0",
                "name": "GPIO 0",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113,
                "xalign": "start",
                "y": 159,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (connected to on-board LED)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO2",
                "name": "GPIO 2",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113,
                "xalign": "start",
                "y": 170,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (outputs PWM signal at boot; be careful: strapping pin;)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO15",
                "name": "GPIO 15",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113,
                "xalign": "start",
                "y": 181,
                "yalign": "start"
            },
			{
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (Attention: do not use, used for SPI Flash!)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO8",
                "name": "GPIO 8",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113,
                "xalign": "start",
                "y": 192,
                "yalign": "start"
            },
			{
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (Attention: do not use, used for SPI Flash!)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO7",
                "name": "GPIO 7",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113,
                "xalign": "start",
                "y": 203,
                "yalign": "start"
            },
			{
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out (Attention: do not use, used for SPI Flash!)",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO6",
                "name": "GPIO 6",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 113,
                "xalign": "start",
                "y": 214,
                "yalign": "start"
            },
        ]
    } as ComponentDataType,
}

