import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType } from '../../types';

export const ESP32C3_supermini: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    data: { 
        name: "compData.ESP32C3_supermini.name",
        description: "compData.ESP32C3_supermini.descriptionShort",
        popover: {
            description: "compData.ESP32C3_supermini.description",
        },
        technicalID: "ESP32C3_supermini",
        technicalVersion: 1,
        group: "controller",
        image: {url:"./ESP32C3_supermini.png", width: 110, height: 83} as ImageDataType,
        rotation: 0,
        resizableX: false,
        rotatable: true,
        borderWidth: 2,
        handles: [
            {
                "borderColor": "#8c8c8c",
                "borderLineWidth": 2,
                "borderRadius": "5%",
                "borderType": "dotted",
                "description": "USB (power and data)",
                "functions": [
                    "usb_in"
                ],
                "height": 40,
                "hid": "USB",
                "name": "USB",
                "position": "left",
                "postype": "left",
                "tolVmax": 5.5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 35,
                "x": 17,
                "xalign": "start",
                "y": 41,
                "yalign": "start"
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "5V",
                "functions": [
                    "suppl_in",
                    "suppl_out"
                ],
                "height": 8,
                "hid": "5V",
                "name": "5V",
                "position": "left",
                "postype": "centered",
                "tolVmax": 5.5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 5,
                "width": 8,
                "x": 14,
                "xalign": "start",
                "y": 6,
                "yalign": "start"
            },
            {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "GND",
                "functions": [
                    "gnd"
                ],
                "height": 8,
                "hid": "GND",
                "name": "GND",
                "position": "left",
                "postype": "centered",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 8,
                "x": 26,
                "xalign": "start",
                "y": 6,
                "yalign": "start"
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "3.3 V",
                "functions": [
                    "suppl_in",
                    "suppl_out"
                ],
                "height": 8,
                "hid": "3V3",
                "name": "3.3 V",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 3,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 38,
                "xalign": "start",
                "y": 6,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO4",
                "name": "GPIO 4",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 50,
                "xalign": "start",
                "y": 6,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO3",
                "name": "GPIO 3",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 8,
                "x": 62,
                "xalign": "start",
                "y": 6,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1); be careful: strapping pin, do not push LOW at boot",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO2",
                "name": "GPIO 2",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 72,
                "xalign": "start",
                "y": 6,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO1",
                "name": "GPIO 1",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 84,
                "xalign": "start",
                "y": 6,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO0",
                "name": "GPIO 0",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 96,
                "xalign": "start",
                "y": 6,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC2)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO5",
                "name": "GPIO 5",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 14,
                "xalign": "start",
                "y": 77,
                "yalign": "start"
            },

            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO6",
                "name": "GPIO 6",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 26,
                "xalign": "start",
                "y": 77,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out; onboard RGB LED",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO7",
                "name": "GPIO 7",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 38,
                "xalign": "start",
                "y": 77,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out; be careful: strapping pin, do not push LOW at boot",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO8",
                "name": "GPIO 8",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 50,
                "xalign": "start",
                "y": 77,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO9",
                "name": "GPIO 9",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 62,
                "xalign": "start",
                "y": 77,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO10",
                "name": "GPIO 10",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 73,
                "xalign": "start",
                "y": 77,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out; be careful: used for USB",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO20",
                "name": "GPIO 20 (RX)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 85,
                "xalign": "start",
                "y": 77,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out; be careful: used for USB",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO21",
                "name": "GPIO 21 (TX)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 97,
                "xalign": "start",
                "y": 77,
                "yalign": "start"
            }
        ]
    } as ComponentDataType,
}

