import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType } from '../../types';

export const ESP32S3D1mini: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    data: { 
        name: "compData.ESP32S3D1mini.name",
        description: "compData.ESP32S3D1mini.descriptionShort",
        popover: {
            description: "compData.ESP32S3D1mini.description",
        },
        technicalID: "ESP32S3D1mini",
        technicalVersion: 1,
        group: "controller",
        image: {url:"./ESP32S3D1mini.jpg", width: 158, height: 122} as ImageDataType,
        rotation: 0,
        resizableX: false,
        rotatable: true,
        borderWidth: 2,
        handles: [
            {
                "borderColor": "#8c8c8c",
                "borderLineWidth": 2,
                "borderRadius": "5%",
                "borderType": "dotted",
                "description": "USB (power and data)",
                "functions": [
                    "usb_in"
                ],
                "height": 40,
                "hid": "USB",
                "name": "USB",
                "position": "left",
                "postype": "left",
                "tolVmax": 5.5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 35,
                "x": 17,
                "xalign": "start",
                "y": 58,
                "yalign": "start"
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "3.3 V",
                "functions": [
                    "suppl_in",
                    "suppl_out"
                ],
                "height": 8,
                "hid": "3V3",
                "name": "3.3 V",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 3,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 40.4,
                "xalign": "start",
                "y": 5.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO10",
                "name": "GPIO 10",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 52.4,
                "xalign": "start",
                "y": 5.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC2)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO11",
                "name": "GPIO 11",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 64.2,
                "xalign": "start",
                "y": 5.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC2)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO13",
                "name": "GPIO 13",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x":76.2,
                "xalign": "start",
                "y": 5.3,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC2)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO12",
                "name": "GPIO 12",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 88,
                "xalign": "start",
                "y": 5.3,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO4",
                "name": "GPIO 4",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 99.9,
                "xalign": "start",
                "y": 5.3,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO2",
                "name": "GPIO 2",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 111.4,
                "xalign": "start",
                "y": 5.4,
                "yalign": "start"
            },
            {
                "borderColor": "blue",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Enable input, disables if pushed LOW",
                "functions": [
                    "rst"
                ],
                "height": 8,
                "hid": "EN",
                "name": "Enable",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 123,
                "xalign": "start",
                "y": 5.4,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC2)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO14",
                "name": "GPIO 14",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 40.6,
                "xalign": "start",
                "y": 17.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO9",
                "name": "GPIO 9",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 52.6,
                "xalign": "start",
                "y": 17.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO8",
                "name": "GPIO 8",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 64.4,
                "xalign": "start",
                "y": 17.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO7",
                "name": "GPIO 7",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 76.2,
                "xalign": "start",
                "y": 17.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO6",
                "name": "GPIO 6",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 88,
                "xalign": "start",
                "y": 17.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO5",
                "name": "GPIO 5",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 99.9,
                "xalign": "start",
                "y": 17.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1); be careful: strapping pin",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO3",
                "name": "GPIO 3",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 111.4,
                "xalign": "start",
                "y": 17.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC1)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO1",
                "name": "GPIO 1",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 123,
                "xalign": "start",
                "y": 17.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC2)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO15",
                "name": "GPIO 15",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 40.8,
                "xalign": "start",
                "y": 99.2,
                "yalign": "start"
            },
            {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "GND",
                "functions": [
                    "gnd"
                ],
                "height": 8,
                "hid": "GND1",
                "name": "GND (1)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 8,
                "x": 52.6,
                "xalign": "start",
                "y": 99.2,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC2)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO17",
                "name": "GPIO 17",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 64.4,
                "xalign": "start",
                "y": 99,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO21",
                "name": "GPIO 21",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 76.2,
                "xalign": "start",
                "y": 99,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO34",
                "name": "GPIO 34",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 88,
                "xalign": "start",
                "y": 99,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO38",
                "name": "GPIO 38",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 99.9,
                "xalign": "start",
                "y": 99,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO37",
                "name": "GPIO 37",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 111.4,
                "xalign": "start",
                "y": 99,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO33",
                "name": "GPIO 33",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 123,
                "xalign": "start",
                "y": 99,
                "yalign": "start"
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "5V",
                "functions": [
                    "suppl_in",
                    "suppl_out"
                ],
                "height": 8,
                "hid": "5V",
                "name": "5V",
                "position": "left",
                "postype": "centered",
                "tolVmax": 5.5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 5,
                "width": 8,
                "x": 40.6,
                "xalign": "start",
                "y": 111,
                "yalign": "start"
            },
            {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "GND",
                "functions": [
                    "gnd"
                ],
                "height": 8,
                "hid": "GND2",
                "name": "GND (2)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 8,
                "x": 52.4,
                "xalign": "start",
                "y": 111,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC2)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO16",
                "name": "GPIO 16",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 64.2,
                "xalign": "start",
                "y": 110.9,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, Analog In (ADC2)",
                "functions": [
                    "dig_in",
                    "dig_out",
                    "an_in"
                ],
                "height": 8,
                "hid": "GPIO18",
                "name": "GPIO 18",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 76.2,
                "xalign": "start",
                "y": 110.8,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO35",
                "name": "GPIO 35",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 88,
                "xalign": "start",
                "y": 110.6,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO36",
                "name": "GPIO 36",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 99.9,
                "xalign": "start",
                "y": 110.6,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO44",
                "name": "GPIO 44",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 111.4,
                "xalign": "start",
                "y": 110.5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO43",
                "name": "GPIO 43",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 123,
                "xalign": "start",
                "y": 110.5,
                "yalign": "start"
            }
        ]
    } as ComponentDataType,
}

