import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType } from '../../types';

export const ESP32D1mini: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    data: { 
        name: "compData.ESP32D1mini.name",
        description: "compData.ESP32D1mini.descriptionShort",
        popover: {
            description: "compData.ESP32D1mini.description",
        },
        technicalID: "ESP32D1mini",
        technicalVersion: 1,
        group: "controller",
        image: {url:"./ESP32D1mini.jpg", width: 83*2, height: 66*2} as ImageDataType,
        rotation: 0,
        resizableX: false,
        rotatable: true,
        borderWidth: 2,
        handles: [
		{
            "borderColor": "#8c8c8c",
            "borderLineWidth": 2,
            "borderRadius": "5%",
            "borderType": "dotted",
            "description": "USB (power and data)",
            "functions": [
                "usb_full"
            ],
            "height": 32,
            "hid": "usb",
            "name": "USB",
            "position": "left",
            "postype": "left",
            "tolVmax": 5,
            "tolVmin": 0,
            "type": "source",
            "Vout": 0,
            "width": 26,
            "x": 12,
            "xalign": "start",
            "y": 65,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In / Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO11",
            "name": "GPIO 11",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 37,
            "xalign": "start",
            "y": 5,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In / Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO9",
            "name": "GPIO 9",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 48,
            "xalign": "start",
            "y": 5,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In / Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO14",
            "name": "GPIO 14",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 69.8,
            "xalign": "start",
            "y": 5,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In (input only)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO34",
            "name": "GPIO 34",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 80.5,
            "xalign": "start",
            "y": 5,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In / Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO33",
            "name": "GPIO 33",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 91.6,
            "xalign": "start",
            "y": 5,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In (input only)",
            "functions": [
                "dig_in"
            ],
            "height": 8,
            "hid": "GPIO35",
            "name": "GPIO 35",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 102.5,
            "xalign": "start",
            "y": 5,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In (input only)",
            "functions": [
                "dig_in"
            ],
            "height": 8,
            "hid": "GPIO39",
            "name": "GPIO 39",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 113,
            "xalign": "start",
            "y": 5,
            "yalign": "start"
        },
        {
            "borderColor": "black",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Ground",
            "functions": [
                "gnd"
            ],
            "height": 8,
            "hid": "GND1",
            "name": "GND (1)",
            "position": "left",
            "postype": "centered",
            "tolVmax": 0,
            "tolVmin": 0,
            "type": "source",
            "Vout": 0,
            "width": 8,
            "x": 135,
            "xalign": "start",
            "y": 5,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out (do not use! connected to the integrated SPI flash)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO10",
            "name": "GPIO 10",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 37,
            "xalign": "start",
            "y": 16,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO13",
            "name": "GPIO 13",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 48,
            "xalign": "start",
            "y": 16,
            "yalign": "start"
        },
        {
            "borderColor": "red",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "3.3 V",
            "functions": [
                "suppl_in",
                "suppl_out"
            ],
            "height": 8,
            "hid": "3V3",
            "name": "3.3 V",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 3,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 59.2,
            "xalign": "start",
            "y": 16,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out (outputs PWM signal at boot; be careful: strapping pin)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO5",
            "name": "GPIO 5",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 69.8,
            "xalign": "start",
            "y": 16,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO23",
            "name": "GPIO 23",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 80.5,
            "xalign": "start",
            "y": 16,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO19",
            "name": "GPIO 19",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 91.6,
            "xalign": "start",
            "y": 16,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO18",
            "name": "GPIO 18",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 102.5,
            "xalign": "start",
            "y": 16,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO26",
            "name": "GPIO 26",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 113,
            "xalign": "start",
            "y": 16,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In, Analog in",
            "functions": [
                "dig_in",
                "an_in"
            ],
            "height": 8,
            "hid": "GPIO36",
            "name": "GPIO 36",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 124,
            "xalign": "start",
            "y": 16,
            "yalign": "start"
        },
        {
            "borderColor": "blue",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Reset input",
            "functions": [
                "rst"
            ],
            "height": 8,
            "hid": "RST",
            "name": "Reset",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 135,
            "xalign": "start",
            "y": 16,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out (do not use! connected to the integrated SPI flash)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO7",
            "name": "GPIO 7",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 37,
            "xalign": "start",
            "y": 115,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out (outputs PWM signal at boot; be careful: strapping pin;)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO15",
            "name": "GPIO 15",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 48,
            "xalign": "start",
            "y": 115,
            "yalign": "start"
        },
        {
            "borderColor": "red",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "5V",
            "functions": [
                "suppl_in",
                "suppl_out"
            ],
            "height": 8,
            "hid": "5V",
            "name": "5V",
            "position": "left",
            "postype": "centered",
            "tolVmax": 5.5,
            "tolVmin": 0,
            "type": "source",
            "Vout": 5,
            "width": 8,
            "x": 59.2,
            "xalign": "start",
            "y": 115,
            "yalign": "start"
        },
        {
            "borderColor": "black",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "GND",
            "functions": [
                "gnd"
            ],
            "height": 8,
            "hid": "GND2",
            "name": "GND (2)",
            "position": "left",
            "postype": "centered",
            "tolVmax": 0,
            "tolVmin": 0,
            "type": "source",
            "Vout": 0,
            "width": 8,
            "x": 69.8,
            "xalign": "start",
            "y": 115,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO16",
            "name": "GPIO 16",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 80.6,
            "xalign": "start",
            "y": 115,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO17",
            "name": "GPIO 17",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 91.6,
            "xalign": "start",
            "y": 115,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO21",
            "name": "GPIO 21",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 102.5,
            "xalign": "start",
            "y": 115,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO22",
            "name": "GPIO 22",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 113,
            "xalign": "start",
            "y": 115,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out (be careful: used for USB!)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO3",
            "name": "GPIO 3",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 124,
            "xalign": "start",
            "y": 115,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out (be careful: used for USB!)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO1",
            "name": "GPIO 1",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 135,
            "xalign": "start",
            "y": 115,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out (do not use! connected to the integrated SPI flash)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO6",
            "name": "GPIO 6",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 37,
            "xalign": "start",
            "y": 126,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out (do not use! connected to the integrated SPI flash)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO8",
            "name": "GPIO 8",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 48,
            "xalign": "start",
            "y": 126,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out (connected to on-board LED)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO2",
            "name": "GPIO 2",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 59.2,
            "xalign": "start",
            "y": 126,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out (outputs PWM signal at boot; be careful: if LOW  at boot, then enters flashing mode)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO0",
            "name": "GPIO 0",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 69.8,
            "xalign": "start",
            "y": 126,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO4",
            "name": "GPIO 4",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 80.6,
            "xalign": "start",
            "y": 126,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out (be careful: boot fails if pulled high, strapping pin)",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO12",
            "name": "GPIO 12",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 91.6,
            "xalign": "start",
            "y": 126,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO32",
            "name": "GPIO 32",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 102.5,
            "xalign": "start",
            "y": 126,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO25",
            "name": "GPIO 25",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 113,
            "xalign": "start",
            "y": 126,
            "yalign": "start"
        },
        {
            "borderColor": "green",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "Digital In/Out",
            "functions": [
                "dig_in",
                "dig_out"
            ],
            "height": 8,
            "hid": "GPIO27",
            "name": "GPIO 27",
            "position": "left",
            "postype": "centered",
            "tolVmax": 3.6,
            "tolVmin": 0,
            "type": "source",
            "Vout": 3.3,
            "width": 8,
            "x": 124,
            "xalign": "start",
            "y": 126,
            "yalign": "start"
        },
        {
            "borderColor": "black",
            "borderLineWidth": 1,
            "borderRadius": "50%",
            "borderType": "dashed",
            "description": "GND",
            "functions": [
                "gnd"
            ],
            "height": 8,
            "hid": "GND3",
            "name": "GND (3)",
            "position": "left",
            "postype": "centered",
            "tolVmax": 0,
            "tolVmin": 0,
            "type": "source",
            "Vout": 0,
            "width": 8,
            "x": 135,
            "xalign": "start",
            "y": 126,
            "yalign": "start"
        }
        ]
    } as ComponentDataType,
}

