import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType } from '../../types';

export const ESP8266D1mini: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    data: { 
        name: "compData.ESP8266D1mini.name",
        description: "compData.ESP8266D1mini.descriptionShort",
        technicalID: "ESP8266D1mini",
        technicalVersion: 1,
        group: "controller",
        image: {url:"./ESP8266D1mini.jpg", width: 162, height: 118} as ImageDataType,
        noBackgroundImageURL: false,
        rotation: 0,
        resizableX: false,
        rotatable: true,
        borderWidth: 2,
        popover: {
            description: "compData.ESP8266D1mini.description",
            buyLinks: []
        },
        handles: [
            {
                "borderColor": "#8c8c8c",
                "borderLineWidth": 2,
                "borderRadius": "5%",
                "borderType": "dotted",
                "description": "USB (power and data)",
                "functions": [
                    "usb_in"
                ],
                "height": 40,
                "hid": "USB",
                "name": "USB",
                "position": "left",
                "postype": "left",
                "tolVmax": 5.5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 8,
                "x": 3,
                "xalign": "start",
                "y": 56,
                "yalign": "start"
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "3.3 V",
                "functions": [
                    "suppl_in",
                    "suppl_out"
                ],
                "height": 8,
                "hid": "3V3",
                "name": "3.3 V",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 3,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 45.5,
                "xalign": "start",
                "y": 5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out; SPI CS",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO15",
                "name": "GPIO 15 (D8)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 57,
                "xalign": "start",
                "y": 5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, SPI MOSI",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO13",
                "name": "GPIO 13 (D7)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 69,
                "xalign": "start",
                "y": 5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, SPI MISO",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO12",
                "name": "GPIO 12 (D6)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 81,
                "xalign": "start",
                "y": 5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, SPI SCLK",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO14",
                "name": "GPIO 14 (D5)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 92.5,
                "xalign": "start",
                "y": 5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, wake up pin",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO16",
                "name": "GPIO 16 (D0)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 104.2,
                "xalign": "start",
                "y": 5,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Analog In",
                "functions": [
                    "an_in"
                ],
                "height": 8,
                "hid": "ADC0",
                "name": "ADC0 (A0)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 8,
                "x": 116,
                "xalign": "start",
                "y": 5,
                "yalign": "start"
            },
            {
                "borderColor": "blue",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Reset input",
                "functions": [
                    "rst"
                ],
                "height": 8,
                "hid": "RST",
                "name": "Reset",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 127.5,
                "xalign": "start",
                "y": 5,
                "yalign": "start"
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "5V",
                "functions": [
                    "suppl_in",
                    "suppl_out"
                ],
                "height": 8,
                "hid": "5V",
                "name": "5V",
                "position": "left",
                "postype": "centered",
                "tolVmax": 5.5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 5,
                "width": 8,
                "x": 45.3,
                "xalign": "start",
                "y": 113,
                "yalign": "start"
            },
            {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "GND",
                "functions": [
                    "gnd"
                ],
                "height": 8,
                "hid": "GND",
                "name": "GND",
                "position": "left",
                "postype": "centered",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 8,
                "x": 56.8,
                "xalign": "start",
                "y": 113,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO2",
                "name": "GPIO 2 (D4)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 68.9,
                "xalign": "start",
                "y": 113,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out; be careful: if LOW during boot, then enters flash mode",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO0",
                "name": "GPIO 0 (D3)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 81,
                "xalign": "start",
                "y": 113,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, I2C SDA",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO4",
                "name": "GPIO 4 (D2)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 92.5,
                "xalign": "start",
                "y": 113,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out, I2C SCL",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO5",
                "name": "GPIO 5 (D1)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 104.2,
                "xalign": "start",
                "y": 113,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out; be careful: used for USB",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO3",
                "name": "GPIO 3 (RX)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 116,
                "xalign": "start",
                "y": 113,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "50%",
                "borderType": "dashed",
                "description": "Digital In/Out; be careful: used for USB",
                "functions": [
                    "dig_in",
                    "dig_out"
                ],
                "height": 8,
                "hid": "GPIO1",
                "name": "GPIO 1 (TX)",
                "position": "left",
                "postype": "centered",
                "tolVmax": 3.6,
                "tolVmin": 0,
                "type": "source",
                "Vout": 3.3,
                "width": 8,
                "x": 127.5,
                "xalign": "start",
                "y": 113,
                "yalign": "start"
            }
        ]
       
    } as ComponentDataType,
}

