import {type Node, Position} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType } from '../../types';

export const FCOB_24V_784LPM: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    origin: [0.5, 0.5],
    data: { 
        image: {url:"./FCOB_24V_784LPM.jpg", width: 182, height: 25} as ImageDataType,
        technicalID: "FCOB_24V_784LPM",
        name: "compData.FCOB_24V_784LPM.name",
        description: "compData.FCOB_24V_784LPM.descriptionShort",
        popover: {
            description: "compData.FCOB_24V_784LPM.description",
        },
        showName: true,
        technicalVersion: 1,
        group: "led",
        rotation: 0,
        rotatable: true,
        borderWidth: 2,
        resizableX: true,
        physLengthStep: 0.016667,
        handles: [
        {
            hid: "24V_start",
            type: "source",
            x: 3.7,
            y: 2.8,
            xalign: "start",
            yalign: "start",
            width: 8,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V pin",
            description: "24V supply input",
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "DATA_start",
            type: "source",
            x: 3.7,
            y: 18,
            xalign: "start",
            yalign: "start",
            width: 8,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA input",
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "GND_start",
            type: "source",
            x: 3.7,
            y: 22.5,
            xalign: "start",
            yalign: "start",
            width: 8,
            height: 5,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "", name: "GND pin",
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "24V_end",
            type: "source",
            x: 3.7,
            y: 2.8,
            xalign: "end",
            yalign: "start",
            width: 8,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V pin",
            description: "24V supply input",
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "DATA_end",
            type: "source",
            x: 3.7,
            y: 18,
            xalign: "end",
            yalign: "start",
            width: 8,
            height: 4,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA output",
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "GND_end",
            type: "source",
            x: 3.7,
            y: 22.5,
            xalign: "end",
            yalign: "start",
            width: 8,
            height: 5,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "GND pin",
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "24V_middle",
            type: "source",
            x: 0,
            y: 2.8,
            xalign: "start",
            yalign: "start",
            width: 12,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "24V pin",
            description: "24V supply input",
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        {
            hid: "DATA_middle",
            type: "source",
            x: 0,
            y: 18,
            xalign: "start",
            yalign: "start",
            width: 12,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA",
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        {
            hid: "GND_middle",
            type: "source",
            x: 0,
            y: 22.5,
            xalign: "start",
            yalign: "start",
            width: 12,
            height: 5,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "GND",
            name: "GND pin",
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        ]
    } as ComponentDataType,
}