import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType, CompInputFieldsBoxType } from '../../types';

export const FUSE_Board: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    data: { 
        name: "compData.FUSE_Board.name",
        description: "compData.FUSE_Board.descriptionShort",
        popover: {
            description: "compData.FUSE_Board.description",
        },
        technicalID: "FUSE_Board",
        technicalVersion: 1,
        group: "electronics",
        image: {url:"./FUSE_Board.jpg", width: 332, height: 198} as ImageDataType,
        rotation: 0,
        resizableX: false,
        rotatable: true,
        borderWidth: 2,
        inputFieldsBox: {
            x: 110,
            y: 83,
            borderType: "transparent",
            borderColor: "black",
            borderLineWidth: 0,
            borderRadius: "0%",
            backgroundColor: "transparent",
            rotate180only: true,
        } as CompInputFieldsBoxType,
        selectFields: [
            {
            technicalID: "Fuse1",
            name: "Fuse1: ",
            displayName: false,
            selectedValue: 10,
            unit: "A",
            fieldWidth: 70,
            customImage: true,
            color: "white",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 78,
                    y: 23,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 78,
                    y: 23,
                },
                {
                    value: 7.5,
                    label: "7.5 A",
                    img: {url:"./miniOTO_7.5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 78,
                    y: 23,
                },
                {
                    value: 10,
                    label: "10 A",
                    img: {url:"./miniOTO_10A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 78,
                    y: 23,
                },
            ],
            },
            {
            technicalID: "Fuse2",
            name: "Fuse2: ",
            displayName: false,
            selectedValue: 10,
            unit: "A",
            fieldWidth: 70,
            customImage: true,
            color: "white",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 186,
                    y: 68,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 186,
                    y: 68,
                },
                {
                    value: 7.5,
                    label: "7.5 A",
                    img: {url:"./miniOTO_7.5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 186,
                    y: 68,
                },
                {
                    value: 10,
                    label: "10 A",
                    img: {url:"./miniOTO_10A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 186,
                    y: 68,
                },
            ],
            },
            {
            technicalID: "Fuse3",
            name: "Fuse3: ",
            displayName: false,
            selectedValue: 10,
            unit: "A",
            fieldWidth: 70,
            customImage: true,
            color: "white",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 78,
                    y: 122,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 78,
                    y: 122,
                },
                {
                    value: 7.5,
                    label: "7.5 A",
                    img: {url:"./miniOTO_7.5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 78,
                    y: 122,
                },
                {
                    value: 10,
                    label: "10 A",
                    img: {url:"./miniOTO_10A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 78,
                    y: 122,
                },
            ],
            },
            {
            technicalID: "Fuse4",
            name: "Fuse4: ",
            displayName: false,
            selectedValue: 10,
            unit: "A",
            fieldWidth: 70,
            customImage: true,
            color: "white",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 186,
                    y: 158,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 186,
                    y: 158,
                },
                {
                    value: 7.5,
                    label: "7.5 A",
                    img: {url:"./miniOTO_7.5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 186,
                    y: 158,
                },
                {
                    value: 10,
                    label: "10 A",
                    img: {url:"./miniOTO_10A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 186,
                    y: 158,
                },
            ],
            },
        ],

        handles: [
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Input 1 (Fuses 1 & 2)",
                "functions": [
                    "suppl_in"
                ],
                "height": 18,
                "hid": "IN1",
                "name": "Input 1",
                "position": "left",
                "postype": "left",
                "tolVmax": 32,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 15,
                "xalign": "start",
                "y": 90,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Input 2 (Fuses 3 & 4)",
                "functions": [
                    "suppl_in"
                ],
                "height": 18,
                "hid": "IN2",
                "name": "Input 2",
                "position": "left",
                "postype": "left",
                "tolVmax": 32,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 15,
                "xalign": "start",
                "y": 113,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Output 1 (Fuse 1)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "OUT1",
                "name": "Output 1",
                "position": "left",
                "postype": "right",
                "tolVmax": 32,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 315,
                "xalign": "start",
                "y": 51,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Output 2 (Fuse 2)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "OUT2",
                "name": "Output 2",
                "position": "left",
                "postype": "right",
                "tolVmax": 32,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 315,
                "xalign": "start",
                "y": 74,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Output 3 (Fuse 3)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "OUT3",
                "name": "Output 3",
                "position": "left",
                "postype": "right",
                "tolVmax": 32,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 315,
                "xalign": "start",
                "y": 122,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Output 4 (Fuse 4)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "OUT4",
                "name": "Output 4",
                "position": "left",
                "postype": "right",
                "tolVmax": 32,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 315,
                "xalign": "start",
                "y": 145,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
        ]
    } as ComponentDataType,
}

