import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType} from '../../types';

export const INMP441: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },

    data: { 
        image: {url:"./INMP441.jpg", width: 60, height: 60} as ImageDataType,
        technicalID: "INMP441",
        name: "compData.INMP441.name",
        description: "compData.INMP441.descriptionShort",
        popover: {
            description: "compData.INMP441.description",
            buyLinks: [{text: "MyHome-Control Shop (Germnany)", url: "https://shop.myhome-control.de/"}]
        },
        technicalVersion: 1,
        group: "electronics",
        rotation: 0,
        borderWidth: 2,
        resizableX: false,
        rotatable: true,
        handles: [
            {
                borderColor: "black",
                borderLineWidth: 0.8,
                borderRadius: "50%",
                borderType: "dotted",
                description: "L/R selection. For WLED must be tied to GND",
                functions: [
                    "dig_in"
                ],
                height: 8,
                hid: "LR",
                name: "L/R",
                position: "left",
                postype: "centered",
                tolVmax: 0,
                tolVmin: 0,
                type: "source",
                Vout: 0,
                width: 8,
                x: 13,
                xalign: "start",
                y: 19,
                yalign: "start",
                prefferedLineWidth: 1,
            } as HandleDataType,
            {
                borderColor: "blue",
                borderLineWidth: 0.8,
                borderRadius: "50%",
                borderType: "dotted",
                description: "WS",
                functions: [
                    "dig_in"
                ],
                height: 8,
                hid: "WS",
                name: "WS",
                position: "left",
                postype: "centered",
                tolVmax: 0,
                tolVmin: 0,
                type: "source",
                Vout: 0,
                width: 8,
                x: 13,
                xalign: "start",
                y: 30,
                yalign: "start",
                prefferedLineWidth: 1,
            } as HandleDataType,
            {
                borderColor: "blue",
                borderLineWidth: 0.8,
                borderRadius: "50%",
                borderType: "dotted",
                description: "SCK",
                functions: [
                    "dig_in"
                ],
                height: 8,
                hid: "SCK",
                name: "SCK",
                position: "left",
                postype: "centered",
                tolVmax: 0,
                tolVmin: 0,
                type: "source",
                Vout: 0,
                width: 8,
                x: 13,
                xalign: "start",
                y: 41,
                yalign: "start",
                prefferedLineWidth: 1,
            } as HandleDataType,
            {
                borderColor: "black",
                borderLineWidth: 0.8,
                borderRadius: "50%",
                borderType: "dotted",
                description: "GND",
                functions: [
                    "gnd"
                ],
                height: 8,
                hid: "GND",
                name: "GND",
                position: "left",
                postype: "centered",
                tolVmax: 0,
                tolVmin: 0,
                type: "source",
                Vout: 0,
                width: 8,
                x: 46.5,
                xalign: "start",
                y: 19,
                yalign: "start",
                prefferedLineWidth: 1,
            } as HandleDataType,
            {
                borderColor: "red",
                borderLineWidth: 0.8,
                borderRadius: "50%",
                borderType: "dotted",
                description: "3.3 V supply",
                functions: [
                    "suppl_in"
                ],
                height: 8,
                hid: "3V3",
                name: "3.3 V",
                position: "left",
                postype: "left",
                tolVmax: 5,
                tolVmin: 0,
                type: "source",
                Vout: 3.3,
                width: 8,
                x: 46.5,
                xalign: "start",
                y: 30,
                yalign: "start",
                prefferedLineWidth: 1,
            } as HandleDataType,
            {
                borderColor: "blue",
                borderLineWidth: 0.8,
                borderRadius: "50%",
                borderType: "dotted",
                description: "Data output",
                functions: [
                    "dig_out"
                ],
                height: 8,
                hid: "SD",
                name: "SD",
                position: "left",
                postype: "centered",
                tolVmax: 0,
                tolVmin: 0,
                type: "source",
                Vout: 0,
                width: 8,
                x: 46.5,
                xalign: "start",
                y: 41,
                yalign: "start",
                prefferedLineWidth: 1,
            } as HandleDataType,
        ]
    } as ComponentDataType,
}