import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType } from '../../types';

export const MHC_RS485_R: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    data: { 
        name: "compData.MHC_RS485_R.name",
        description: "compData.MHC_RS485_R.descriptionShort",
        popover: {
            description: "compData.MHC_RS485_R.description",
            buyLinks: [{text: "MyHome-Control Shop (Germnany)", url: "https://shop.myhome-control.de/"}]
        },
        technicalID: "MHC_RS485_R",
        technicalVersion: 1,
        group: "electronics",
        image: {url:"./MHC_RS485_R.png", width: 178, height: 54} as ImageDataType,
        rotation: 0,
        resizableX: false,
        rotatable: true,
        borderWidth: 2,
        handles: [
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dotted",
                "description": "RS-485 input A",
                "functions": [
                    "rs485_A"
                ],
                "height": 14,
                "hid": "RS485A",
                "name": "RS-485 input A",
                "position": "left",
                "postype": "left",
                "tolVmax": 24,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 24,
                "x": 16,
                "xalign": "start",
                "y": 10,
                "yalign": "start",
                "prefferedLineWidth": 2
            },
           {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dotted",
                "description": "RS-485 GND",
                "functions": [
                    "gnd"
                ],
                "height": 14,
                "hid": "RS485GND",
                "name": "GND (RS-485)", 
                "position": "left",
                "postype": "left",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 24,
                "x": 16,
                "xalign": "start",
                "y": 26,
                "yalign": "start",
                "prefferedLineWidth": 2,
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dotted",
                "description": "RS-485 input B",
                "functions": [
                    "rs485_B"
                ],
                "height": 14,
                "hid": "RS485B",
                "name": "RS-485 input B",
                "position": "left",
                "postype": "left",
                "tolVmax": 24,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 24,
                "x": 16,
                "xalign": "start",
                "y": 41,
                "yalign": "start",
                "prefferedLineWidth": 2
            },
            
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dotted",
                "description": "Power input (from LEDs)",
                "functions": [
                    "suppl_out"
                ],
                "height": 14,
                "hid": "VIN",
                "name": "Power input +",
                "position": "left",
                "postype": "right",
                "tolVmax": 24,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 24,
                "x": 161,
                "xalign": "start",
                "y": 42,
                "yalign": "start",
                "prefferedLineWidth": 2,
            },
           {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dotted",
                "description": "GND",
                "functions": [
                    "gnd"
                ],
                "height": 14,
                "hid": "GND1",
                "name": "GND (from LEDs)",
                "position": "left",
                "postype": "right",
                "tolVmax": 26,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 24,
                "x": 161,
                "xalign": "start",
                "y": 10,
                "yalign": "start",
                "prefferedLineWidth": 2,
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dotted",
                "description": "Data output",
                "functions": [
                    "dig_out"
                ],
                "height": 14,
                "hid": "DAT",
                "name": "Data output",
                "position": "left",
                "postype": "right",
                "tolVmax": 5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 5,
                "width": 24,
                "x": 161,
                "xalign": "start",
                "y": 26,
                "yalign": "start",
                "prefferedLineWidth": 2,
            },
        ]
    } as ComponentDataType,
}

