import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType, CompInputFieldsBoxType } from '../../types';

export const MHC_PWMBoard: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    data: { 
        name: "compData.MHC_PWMBoard.name",
        description: "compData.MHC_PWMBoard.descriptionShort",
        popover: {
            description: "compData.MHC_PWMBoard.description",
            buyLinks: [{text: "MyHome-Control Shop (Germnany)", url: "https://shop.myhome-control.de/"}]
        },
        technicalID: "MHC_PWMBoard",
        technicalVersion: 1,
        group: "electronics",
        image: {url:"./MHC_PWMBoard.jpg", width: 332, height: 198} as ImageDataType,
        rotation: 0,
        resizableX: false,
        rotatable: true,
        borderWidth: 2,
        inputFieldsBox: {
            x: 156,
            y: 85,
            borderType: "transparent",
            borderColor: "black",
            borderLineWidth: 0,
            borderRadius: "0%",
            backgroundColor: "transparent",
            backgroundColorSelected: "white",
            rotate180only: true,
        } as CompInputFieldsBoxType,
        selectFields: [
            {
            technicalID: "Fuse",
            name: "Fuse: ",
            displayName: false,
            selectedValue: 15,
            unit: "A",
            fieldWidth: 107,
            customImage: true,
            color: "black",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 2,
                    label: "2 A",
                    img: {url:"./miniOTO_2A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 85,
                    y: 5,
                },
                {
                    value: 3,
                    label: "3 A",
                    img: {url:"./miniOTO_3A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 85,
                    y: 5,
                },
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 85,
                    y: 5,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 85,
                    y: 5,
                },
                {
                    value: 7.5,
                    label: "7.5 A",
                    img: {url:"./miniOTO_7.5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 85,
                    y: 5,
                },
                {
                    value: 10,
                    label: "10 A",
                    img: {url:"./miniOTO_10A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 85,
                    y: 5,
                },
                {
                    value: 15,
                    label: "15 A",
                    img: {url:"./miniOTO_15A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 85,
                    y: 5,
                },
            ],
            },
            {
            technicalID: "Fuse1",
            name: "Fuse1: ",
            displayName: false,
            selectedValue: 5,
            unit: "A",
            fieldWidth: 107,
            customImage: true,
            color: "black",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 2,
                    label: "2 A",
                    img: {url:"./miniOTO_2A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 40,
                },
                {
                    value: 3,
                    label: "3 A",
                    img: {url:"./miniOTO_3A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 198,
                    y: 84,
                },
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 198,
                    y: 84,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 198,
                    y: 84,
                },
            ],
            },
            {
            technicalID: "Fuse2",
            name: "Fuse2: ",
            displayName: false,
            selectedValue: 5,
            unit: "A",
            fieldWidth: 107,
            customImage: true,
            color: "black",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 2,
                    label: "2 A",
                    img: {url:"./miniOTO_2A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 198,
                    y: 123,
                },
                {
                    value: 3,
                    label: "3 A",
                    img: {url:"./miniOTO_3A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 198,
                    y: 123,
                },
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 198,
                    y: 123,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 198,
                    y: 123,
                },
            ],
            },
            {
            technicalID: "Fuse3",
            name: "Fuse3: ",
            displayName: false,
            selectedValue: 5,
            unit: "A",
            fieldWidth: 107,
            customImage: true,
            color: "black",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 2,
                    label: "2 A",
                    img: {url:"./miniOTO_2A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 222,
                    y: 166,
                },
                {
                    value: 3,
                    label: "3 A",
                    img: {url:"./miniOTO_3A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 222,
                    y: 166,
                },
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 222,
                    y: 166,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 222,
                    y: 166,
                },
            ],
            },           
        ],

        handles: [
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "power supply in +",
                "functions": [
                    "suppl_in"
                ],
                "height": 18,
                "hid": "VIN",
                "name": "Power supply input +",
                "position": "left",
                "postype": "left",
                "tolVmax": 48,
                "tolVmin": 12,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 20,
                "xalign": "start",
                "y": 43,
                "yalign": "start",
                "prefferedLineWidth": 4
            },
           {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "GND",
                "functions": [
                    "gnd"
                ],
                "height": 18,
                "hid": "GND",
                "name": "GND (input)", 
                "position": "left",
                "postype": "left",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 20,
                "xalign": "start",
                "y": 65,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "PWM input 1",
                "functions": [
                    "dig_in"
                ],
                "height": 18,
                "hid": "PWMIN1",
                "name": "PWM input 1",
                "position": "left",
                "postype": "left",
                "tolVmax": 5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 20,
                "xalign": "start",
                "y": 87,
                "yalign": "start",
                "prefferedLineWidth": 2,
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "PWM input 2",
                "functions": [
                    "dig_in"
                ],
                "height": 18,
                "hid": "PWMIN2",
                "name": "PWM input 2",
                "position": "left",
                "postype": "left",
                "tolVmax": 5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 20,
                "xalign": "start",
                "y": 109,
                "yalign": "start",
                "prefferedLineWidth": 2,
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "PWM input 3",
                "functions": [
                    "dig_in"
                ],
                "height": 18,
                "hid": "PWMIN3",
                "name": "PWM input 3",
                "position": "left",
                "postype": "left",
                "tolVmax": 5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 20,
                "xalign": "start",
                "y": 131,
                "yalign": "start",
                "prefferedLineWidth": 2,
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Power output + (fused)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "VOUT",
                "name": "Power output +",
                "position": "left",
                "postype": "right",
                "tolVmax": 48,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 312,
                "xalign": "start",
                "y": 48,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
           {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "PWM Output 1",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "PWMOUT1",
                "name": "PWM output 1",
                "position": "left",
                "postype": "right",
                "tolVmax": 48,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 312,
                "xalign": "start",
                "y": 70,
                "yalign": "start",
                "prefferedLineWidth": 3,
            },
            {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "PWM Output 2",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "PWMOUT2",
                "name": "PWM output 2",
                "position": "left",
                "postype": "right",
                "tolVmax": 48,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 312,
                "xalign": "start",
                "y": 91,
                "yalign": "start",
                "prefferedLineWidth": 3,
            },
            {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "PWM Output 3",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "PWMOUT3",
                "name": "PWM output 3",
                "position": "left",
                "postype": "right",
                "tolVmax": 48,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 312,
                "xalign": "start",
                "y": 113,
                "yalign": "start",
                "prefferedLineWidth": 3,
            },
        ]
    } as ComponentDataType,
}

