import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType, CompInputFieldsBoxType } from '../../types';

export const MHC_SwitchBoard: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    data: { 
        name: "compData.MHC_SwitchBoard.name",
        description: "compData.MHC_SwitchBoard.descriptionShort",
        popover: {
            description: "compData.MHC_SwitchBoard.description",
            buyLinks: [{text: "MyHome-Control Shop (Germnany)", url: "https://shop.myhome-control.de/"}]
        },
        technicalID: "MHC_SwitchBoard",
        technicalVersion: 1,
        group: "electronics",
        image: {url:"./MHC_SwitchBoard.png", width: 332, height: 198} as ImageDataType,
        rotation: 0,
        resizableX: false,
        rotatable: true,
        borderWidth: 2,
        inputFieldsBox: {
            x: 200,
            y: 85,
            borderType: "transparent",
            borderColor: "black",
            borderLineWidth: 0,
            borderRadius: "0%",
            backgroundColor: "transparent",
            backgroundColorSelected: "white",
            rotate180only: true,
        } as CompInputFieldsBoxType,
        selectFields: [
            {
            technicalID: "Fuse1",
            name: "Fuse1: ",
            displayName: false,
            selectedValue: 5,
            unit: "A",
            fieldWidth: 107,
            customImage: true,
            color: "black",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 2,
                    label: "2 A",
                    img: {url:"./miniOTO_2A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 40,
                },
                {
                    value: 3,
                    label: "3 A",
                    img: {url:"./miniOTO_3A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 40,
                },
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 40,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 40,
                },
            ],
            },
            {
            technicalID: "Fuse2",
            name: "Fuse2: ",
            displayName: false,
            selectedValue: 10,
            unit: "A",
            fieldWidth: 107,
            customImage: true,
            color: "black",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 2,
                    label: "2 A",
                    img: {url:"./miniOTO_2A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 107,
                },
                {
                    value: 3,
                    label: "3 A",
                    img: {url:"./miniOTO_3A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 107,
                },
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 107,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 107,
                },
                {
                    value: 7.5,
                    label: "7.5 A",
                    img: {url:"./miniOTO_7.5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 107,
                },
                {
                    value: 10,
                    label: "10 A",
                    img: {url:"./miniOTO_10A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 107,
                },
            ],
            },
            {
            technicalID: "Fuse3",
            name: "Fuse3: ",
            displayName: false,
            selectedValue: 5,
            unit: "A",
            fieldWidth: 107,
            customImage: true,
            color: "black",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 2,
                    label: "2 A",
                    img: {url:"./miniOTO_2A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 168,
                },
                {
                    value: 3,
                    label: "3 A",
                    img: {url:"./miniOTO_3A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 168,
                },
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 168,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 88,
                    y: 168,
                },
            ],
            },           
        ],

        handles: [
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "power supply in +",
                "functions": [
                    "suppl_in"
                ],
                "height": 22,
                "hid": "VIN",
                "name": "Power supply input +",
                "position": "left",
                "postype": "left",
                "tolVmax": 24,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 40,
                "x": 25,
                "xalign": "start",
                "y": 145,
                "yalign": "start",
                "prefferedLineWidth": 4
            },
           {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "GND",
                "functions": [
                    "gnd"
                ],
                "height": 22,
                "hid": "GND",
                "name": "GND (input)", 
                "position": "left",
                "postype": "left",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 40,
                "x": 25,
                "xalign": "start",
                "y": 116,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Enable input",
                "functions": [
                    "dig_in"
                ],
                "height": 14,
                "hid": "EN1",
                "name": "Enable input",
                "position": "left",
                "postype": "left",
                "tolVmax": 5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 22,
                "x": 21,
                "xalign": "start",
                "y": 75,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Enable input",
                "functions": [
                    "dig_in"
                ],
                "height": 14,
                "hid": "EN2",
                "name": "Enable input",
                "position": "left",
                "postype": "left",
                "tolVmax": 5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 22,
                "x": 21,
                "xalign": "start",
                "y": 91,
                "yalign": "start"
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Power output 1 (fused, switched)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "VOUT1",
                "name": "Power output 1",
                "position": "left",
                "postype": "right",
                "tolVmax": 26,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 314,
                "xalign": "start",
                "y": 151,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
           {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "GND (output 1)",
                "functions": [
                    "gnd"
                ],
                "height": 18,
                "hid": "GND1",
                "name": "GND (output 1)",
                "position": "left",
                "postype": "right",
                "tolVmax": 26,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 314,
                "xalign": "start",
                "y": 129,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Power output 2 (fused, switched)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "VOUT2",
                "name": "Power output 2",
                "position": "left",
                "postype": "right",
                "tolVmax": 26,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 314,
                "xalign": "start",
                "y": 107,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
           {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "GND (output 2)",
                "functions": [
                    "gnd"
                ],
                "height": 18,
                "hid": "GND2",
                "name": "GND (output 2)",
                "position": "left",
                "postype": "right",
                "tolVmax": 26,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 314,
                "xalign": "start",
                "y": 85,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
 {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Power output 3 (fused, switched)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "VOUT3",
                "name": "Power output 3",
                "position": "left",
                "postype": "right",
                "tolVmax": 26,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 314,
                "xalign": "start",
                "y": 63,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
           {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "GND (output 3)",
                "functions": [
                    "gnd"
                ],
                "height": 18,
                "hid": "GND3",
                "name": "GND (output 3)",
                "position": "left",
                "postype": "right",
                "tolVmax": 26,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 314,
                "xalign": "start",
                "y": 41,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
        ]
    } as ComponentDataType,
}

