import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType, CompInputFieldsBoxType } from '../../types';

export const MHC_Relay12V: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    data: { 
        name: "compData.MHC_Relay12V.name",
        description: "compData.MHC_Relay12V.descriptionShort",
        popover: {
            description: "compData.MHC_Relay12V.description",
            buyLinks: [{text: "MyHome-Control Shop (Germnany)", url: "https://shop.myhome-control.de/"}]
        },
        technicalID: "MHC_Relay12V",
        technicalVersion: 1,
        group: "electronics",
        image: {url:"./MHC_Relay12V.png", width: 332, height: 198} as ImageDataType,
        rotation: 0,
        resizableX: false,
        rotatable: true,
        borderWidth: 2,
        inputFieldsBox: {
            x: 120,
            y: 83,
            borderType: "transparent",
            borderColor: "black",
            borderLineWidth: 0,
            borderRadius: "0%",
            backgroundColor: "transparent",
            backgroundColorSelected: "white",
            rotate180only: true,
        } as CompInputFieldsBoxType,
        selectFields: [
            {
            technicalID: "Fuse1",
            name: "Fuse1: ",
            displayName: false,
            selectedValue: 10,
            unit: "A",
            fieldWidth: 100,
            customImage: true,
            color: "black",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 83,
                    y: 43,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 83,
                    y: 43,
                },
                {
                    value: 7.5,
                    label: "7.5 A",
                    img: {url:"./miniOTO_7.5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 83,
                    y: 43,
                },
                {
                    value: 10,
                    label: "10 A",
                    img: {url:"./miniOTO_10A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 83,
                    y: 43,
                },
            ],
            },
            {
            technicalID: "Fuse2",
            name: "Fuse2: ",
            displayName: false,
            selectedValue: 10,
            unit: "A",
            fieldWidth: 100,
            customImage: true,
            color: "black",
            hide: true,
            showNameIfSelected:true,
            options: [
                {
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 133,
                    y: 9,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 83,
                    y: 136,
                },
                {
                    value: 7.5,
                    label: "7.5 A",
                    img: {url:"./miniOTO_7.5A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 83,
                    y: 136,
                },
                {
                    value: 10,
                    label: "10 A",
                    img: {url:"./miniOTO_10A_top.jpg", width: 60, height: 20} as ImageDataType,
                    x: 83,
                    y: 136,
                },
            ],
            },             
        ],

        handles: [
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "12 V DC power supply",
                "functions": [
                    "suppl_in"
                ],
                "height": 18,
                "hid": "VIN1",
                "name": "Power supply input",
                "position": "left",
                "postype": "left",
                "tolVmax": 14,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 20,
                "xalign": "start",
                "y": 40.5,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "12 V DC power supply",
                "functions": [
                    "suppl_in"
                ],
                "height": 18,
                "hid": "VIN2",
                "name": "Power supply input",
                "position": "left",
                "postype": "left",
                "tolVmax": 14,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 20,
                "xalign": "start",
                "y": 62,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Control input for relay 1",
                "functions": [
                    "dig_in"
                ],
                "height": 18,
                "hid": "CTRL1",
                "name": "Control input 1",
                "position": "left",
                "postype": "left",
                "tolVmax": 5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 20,
                "xalign": "start",
                "y": 88,
                "yalign": "start"
            },
            {
                "borderColor": "green",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Control input for relay 2",
                "functions": [
                    "dig_in"
                ],
                "height": 18,
                "hid": "CTRL2",
                "name": "Control input 2",
                "position": "left",
                "postype": "left",
                "tolVmax": 5,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 20,
                "xalign": "start",
                "y": 109,
                "yalign": "start"
            },
           {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "GND",
                "functions": [
                    "gnd"
                ],
                "height": 18,
                "hid": "GND1",
                "name": "GND (input)", 
                "position": "left",
                "postype": "left",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 20,
                "xalign": "start",
                "y": 135,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "black",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "GND",
                "functions": [
                    "gnd"
                ],
                "height": 18,
                "hid": "GND2",
                "name": "GND (input)", 
                "position": "left",
                "postype": "left",
                "tolVmax": 0,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 20,
                "xalign": "start",
                "y": 156,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
            {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Power output (fused, enabled when no control signal)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "VOUT1",
                "name": "Power output 1 (NC)",
                "position": "left",
                "postype": "right",
                "tolVmax": 26,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 311,
                "xalign": "start",
                "y": 48,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
           {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Power output (fused, enabled when control signal applied)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "VOUT2",
                "name": "Power output 1 (NO)",
                "position": "left",
                "postype": "right",
                "tolVmax": 26,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 311,
                "xalign": "start",
                "y": 69,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
                        {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Power output (fused, enabled when no control signal)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "VOUT3",
                "name": "Power output 2 (NC)",
                "position": "left",
                "postype": "right",
                "tolVmax": 26,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 311,
                "xalign": "start",
                "y": 95,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
           {
                "borderColor": "red",
                "borderLineWidth": 1,
                "borderRadius": "20%",
                "borderType": "dashed",
                "description": "Power output (fused, enabled when control signal applied)",
                "functions": [
                    "suppl_out"
                ],
                "height": 18,
                "hid": "VOUT4",
                "name": "Power output 2 (NO)",
                "position": "left",
                "postype": "right",
                "tolVmax": 26,
                "tolVmin": 0,
                "type": "source",
                "Vout": 0,
                "width": 30,
                "x": 311,
                "xalign": "start",
                "y": 116,
                "yalign": "start",
                "prefferedLineWidth": 4,
            },
        ]
    } as ComponentDataType,
}

