import {type Node, Position} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType, CompInputFieldsBoxType } from '../../types';

export const miniOTOFuse: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    data: { 
        image: {url:"./miniOTO_5A.jpg", width: 60, height: 89} as ImageDataType,
        technicalID: "miniOTOFuse",
        name: "compData.miniOTOFuse.name",
        description: "compData.miniOTOFuse.descriptionShort",
        popover: {
            description: "compData.miniOTOFuse.description",
            buyLinks: [
                {text: "MyHome-Control Shop (Germnany)", url: "https://shop.myhome-control.de/"},
            ]
        },
        technicalVersion: 1,
        group: "electronics",
        rotation: 0,
        borderWidth: 2,
        resizableX: false,
        rotatable: true,
        physLengthStep: 0.016667,
        inputFieldsBox: {
            x: 31,
            y: 25.5,
            borderType: "transparent",
            borderColor: "black",
            borderLineWidth: 0,
            borderRadius: "0%",
            backgroundColor: "transparent",
            rotate180only: true,
        } as CompInputFieldsBoxType,
        selectFields: [
            {
            technicalID: "NominalValue",
            name: "I",
            displayName: false,
            selectedValue: 5,
            unit: "A",
            fieldWidth: 70,
            customImage: true,
            color: "white",
            options: [
                {
                    value: 2,
                    label: "2 A",
                    img: {url:"./miniOTO_2A.jpg", width: 60, height: 89} as ImageDataType,
                    x: 0,
                    y:0,
                },
				{
                    value: 3,
                    label: "3 A",
                    img: {url:"./miniOTO_3A.jpg", width: 60, height: 89} as ImageDataType,
                    x: 0,
                    y:0,
                },
				{
                    value: 4,
                    label: "4 A",
                    img: {url:"./miniOTO_4A.jpg", width: 60, height: 89} as ImageDataType,
                    x: 0,
                    y:0,
                },
                {
                    value: 5,
                    label: "5 A",
                    img: {url:"./miniOTO_5A.jpg", width: 60, height: 89} as ImageDataType,
                    x: 0,
                    y:0,
                },
                {
                    value: 7.5,
                    label: "7.5 A",
                    img: {url:"./miniOTO_7.5A.jpg", width: 60, height: 89} as ImageDataType,
                    x: 0,
                    y:0,
                },
                {
                    value: 10,
                    label: "10 A",
                    img: {url:"./miniOTO_10A.jpg", width: 60, height: 89} as ImageDataType,
                    x: 0,
                    y:0,
                },
                {
                    value: 15,
                    label: "15 A",
                    img: {url:"./miniOTO_15A.jpg", width: 60, height: 89} as ImageDataType,
                    x: 0,
                    y:0,
                },
                {
                    value: 20,
                    label: "20 A",
                    img: {url:"./miniOTO_20A.jpg", width: 60, height: 89} as ImageDataType,
                    x: 0,
                    y:0,
                },
                {
                    value: 30,
                    label: "30 A",
                    img: {url:"./miniOTO_30A.jpg", width: 60, height: 89} as ImageDataType,
                    x: 0,
                    y:0,
                }
            ],
            },
        ],
        handles: [
        {
            hid: "1",
            type: "source",
            x: 6.8,
            y: 79,
            xalign: "start",
            yalign: "start",
            width: 15,
            height: 20,
            borderType: "dashed",
            borderColor: "red",
            borderLineWidth: 0.5,
            borderRadius: "10%",
            postype: "bottom",
            position: Position.Left,
            description: "1",
            name: "1",
            prefferedLineWidth: 4,
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "2",
            type: "source",
            x: 52.2,
            y: 79,
            xalign: "start",
            yalign: "start",
            width: 15,
            height: 20,
            borderType: "dashed",
            borderColor: "red",
            borderLineWidth: 0.5,
            borderRadius: "10%",
            postype: "bottom",
            position: Position.Left,
            description: "2",
            name: "2",
            prefferedLineWidth: 4,
            prefferedLineDirection: "right",
        } as HandleDataType,
        ]
    } as ComponentDataType,
}