import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType} from '../../types';

export const PIR_HCSR501: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    origin: [0.5, 0.5],
    data: { 
        image: {url:"./PIR_HCSR501.png", width: 128, height: 146} as ImageDataType,
        technicalID: "PIR_HCSR501",
        name: "compData.PIR_HCSR501.name",
        description: "compData.PIR_HCSR501.descriptionShort",
        popover: {
            description: "compData.PIR_HCSR501.description",
        },
        technicalVersion: 1,
        group: "electronics",
        rotation: 0,
        borderWidth: 2,
        resizableX: false,
        rotatable: true,
        handles: [
            {
                borderColor: "black",
                borderLineWidth: 0.8,
                borderRadius: "20%",
                borderType: "dotted",
                description: "GND",
                functions: [
                    "gnd"
                ],
                height: 6,
                hid: "GND",
                name: "GND",
                position: "left",
                postype: "left",
                tolVmax: 0,
                tolVmin: 0,
                type: "source",
                Vout: 0,
                width: 12,
                x: 13,
                xalign: "start",
                y: 61,
                yalign: "start",
                prefferedLineWidth: 1,
            } as HandleDataType,
            {
                borderColor: "green",
                borderLineWidth: 0.8,
                borderRadius: "20%",
                borderType: "dotted",
                description: "Output",
                functions: [
                    "dig_out"
                ],
                height: 6,
                hid: "OUT",
                name: "OUT",
                position: "left",
                postype: "left",
                tolVmax: 5,
                tolVmin: 0,
                type: "source",
                Vout: 3.3,
                width: 12,
                x: 13,
                xalign: "start",
                y: 72.2,
                yalign: "start",
                prefferedLineWidth: 1,
            } as HandleDataType,
            {
                borderColor: "red",
                borderLineWidth: 0.8,
                borderRadius: "20%",
                borderType: "dotted",
                description: "Supply voltage (5-12V)",
                functions: [
                    "suppl_in"
                ],
                height: 6,
                hid: "V",
                name: "+V",
                position: "left",
                postype: "left",
                tolVmax: 12,
                tolVmin: 0,
                type: "source",
                Vout: 0,
                width: 12,
                x: 13,
                xalign: "start",
                y: 83.3,
                yalign: "start",
                prefferedLineWidth: 1,
            } as HandleDataType,
        ]
    } as ComponentDataType,
}