import {type Node, Position} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType} from '../../types';

export const PLUG_LNPE: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    origin: [0.5, 0.5],
    data: { 
        image: {url:"./Plug_LNPE.jpg", width: 120, height: 60} as ImageDataType,
        technicalID: "PLUG_LNPE",
        name: "compData.PLUG_LNPE.name",
        description: "compData.PLUG_LNPE.descriptionShort",
        popover: {
            description: "compData.PLUG_LNPE.description",
        },
        technicalVersion: 1,
        group: "psu",
        rotation: 0,
        borderWidth: 2,
        resizableX: false,
        rotatable: true,
        handles: [
        {
            hid: "L",
            type: "source",
            x: 117,
            y: 18.5,
            xalign: "start",
            yalign: "start",
            width: 8,
            height: 8,
            borderType: "dashed",
            borderColor: "#005ce6",
            borderLineWidth: 0.8,
            borderRadius: "20%",
            postype: "right",
            position: Position.Left,
            name: "L",
            description: "Line 110~V/230~V",
            functions: ["line"],
            prefferedLineWidth: 3,
        } as HandleDataType,
        {
            hid: "N",
            type: "source",
            x: 117,
            y: 29,
            xalign: "start",
            yalign: "start",
            width: 8,
            height: 8,
            borderType: "dashed",
            borderColor: "#996600",
            borderLineWidth: 0.8,
            borderRadius: "20%",
            postype: "right",
            position: Position.Left,
            name: "N",
            description: "Neutral 110~V/230~V",
            functions: ["neutral"],
            prefferedLineWidth: 3,
        } as HandleDataType,
        {
            hid: "PE",
            type: "source",
            x: 117,
            y: 39.5,
            xalign: "start",
            yalign: "start",
            width: 8,
            height: 8,
            borderType: "dashed",
            borderColor: "#ccff33",
            borderLineWidth: 0.8,
            borderRadius: "20%",
            postype: "right",
            position: Position.Left,
            name: "PE",
            description: "Protective earth",
            functions: ["pe"],
            prefferedLineWidth: 3,
        } as HandleDataType,


        ]
    } as ComponentDataType,
}