import {type Node} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType} from '../../types';

export const SN74AHCT125N: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    origin: [0.5, 0.5],
    data: { 
        image: {url:"./SN74AHCT125N.jpg", width: 40, height: 97} as ImageDataType,
        technicalID: "SN74AHCT125N",
        name: "compData.SN74AHCT125N.name",
        description: "compData.SN74AHCT125N.descriptionShort",
        popover: {
            description: "compData.SN74AHCT125N.description",
        },
        technicalVersion: 1,
        group: "levelshifter",
        rotation: 0,
        borderWidth: 2,
        resizableX: false,
        rotatable: true,
        handles: [
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Output 1 enable (inverted)",
            functions: [
                "dig_in"
            ],
            height: 8,
            hid: "1OE",
            name: "/1OE",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 4,
            x: 2,
            xalign: "start",
            y: 10,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Input 1",
            functions: [
                "dig_in"
            ],
            height: 8,
            hid: "1A",
            name: "1A",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 4,
            x: 2,
            xalign: "start",
            y: 23,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Output 1",
            functions: [
                "dig_out"
            ],
            height: 8,
            hid: "1Y",
            name: "1Y",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 5,
            width: 4,
            x: 2,
            xalign: "start",
            y: 35.6,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Output 2 enable (inverted)",
            functions: [
                "dig_in"
            ],
            height: 8,
            hid: "2OE",
            name: "/2OE",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 4,
            x: 2,
            xalign: "start",
            y: 48.5,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Input 2",
            functions: [
                "dig_in"
            ],
            height: 8,
            hid: "2A",
            name: "2A",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 4,
            x: 2,
            xalign: "start",
            y: 61,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Output 2",
            functions: [
                "dig_out"
            ],
            height: 8,
            hid: "2Y",
            name: "2Y",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 5,
            width: 4,
            x: 2,
            xalign: "start",
            y: 74,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "GND",
            functions: [
                "gnd"
            ],
            height: 8,
            hid: "GND",
            name: "GND",
            position: "left",
            postype: "centered",
            tolVmax: 0,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 4,
            x: 2,
            xalign: "start",
            y: 87,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Voltage supply",
            functions: [
                "suppl_in"
            ],
            height: 8,
            hid: "VCC",
            name: "VCC",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 4,
            x: 38,
            xalign: "start",
            y: 10,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Output 4 enable (inverted)",
            functions: [
                "dig_in"
            ],
            height: 8,
            hid: "4OE",
            name: "/4OE",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 4,
            x: 38,
            xalign: "start",
            y: 23,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Input 4",
            functions: [
                "dig_in"
            ],
            height: 8,
            hid: "4A",
            name: "4A",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 4,
            x: 38,
            xalign: "start",
            y: 35.6,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Output 4",
            functions: [
                "dig_out"
            ],
            height: 8,
            hid: "4Y",
            name: "4Y",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 5,
            width: 4,
            x: 38,
            xalign: "start",
            y: 48.5,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Output 3 enable (inverted)",
            functions: [
                "dig_in"
            ],
            height: 8,
            hid: "3OE",
            name: "/3OE",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 4,
            x: 38,
            xalign: "start",
            y: 61,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Input 3",
            functions: [
                "dig_in"
            ],
            height: 8,
            hid: "3A",
            name: "3A",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 0,
            width: 4,
            x: 38,
            xalign: "start",
            y: 74,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        {
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "5%",
            borderType: "dotted",
            description: "Output 3",
            functions: [
                "dig_out"
            ],
            height: 8,
            hid: "3Y",
            name: "3Y",
            position: "left",
            postype: "centered",
            tolVmax: 5,
            tolVmin: 0,
            type: "source",
            Vout: 5,
            width: 4,
            x: 38,
            xalign: "start",
            y: 87,
            yalign: "start",
            prefferedLineWidth: 1,
        } as HandleDataType,
        ]
    } as ComponentDataType,
}