import {type Node, Position} from '@xyflow/react';
import {ComponentDataType, ImageDataType, HandleDataType } from '../../types';

export const WS2812B_5V_30LPM: Node = {
    id: '',
    type: 'general-component-type',
    position: { x: 0, y: 0 },
    origin: [0.5, 0.5],
    data: { 
        image: {url:"./WS2812B_5V_30LPM.png", width: 85, height: 25} as ImageDataType,
        technicalID: "WS2812B_5V_30LPM",
        name: "compData.WS2812B_5V_30LPM.name",
        description: "compData.WS2812B_5V_30LPM.descriptionShort",
        popover: {
            description: "compData.WS2812B_5V_30LPM.description",
        },
        showName: true,
        technicalVersion: 1,
        group: "led",
        rotation: 0,
        rotatable: true,
        borderWidth: 2,
        resizableX: true,
        physLengthStep: 0.016667,
       handles: [
        {
            hid: "5V_start",
            type: "source",
            x: 2.7,
            y: 19.2,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "5V pin",
            description: "5V supply input",
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "DATA_start",
            type: "source",
            x: 2.7,
            y: 12.6,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA input",
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "GND_start",
            type: "source",
            x: 2.7,
            y: 6.1,
            xalign: "start",
            yalign: "start",
            width: 6,
            height: 4,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "", name: "GND pin",
            prefferedLineDirection: "left",
        } as HandleDataType,
        {
            hid: "5V_end",
            type: "source",
            x: 2.7,
            y: 19.2,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "5V pin",
            description: "5V supply input",
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "DATA_end",
            type: "source",
            x: 2.7,
            y: 12.6,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA output",
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "GND_end",
            type: "source",
            x: 2.7,
            y: 6.1,
            xalign: "end",
            yalign: "start",
            width: 6,
            height: 4,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "GND pin",
            prefferedLineDirection: "right",
        } as HandleDataType,
        {
            hid: "5V_middle",
            type: "source",
            x: 0,
            y: 19.2,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 5,
            borderType: "dotted",
            borderColor: "red",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            name: "5V pin",
            description: "5V supply input",
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        {
            hid: "DATA_middle",
            type: "source",
            x: 0,
            y: 12.6,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 5,
            borderType: "dotted",
            borderColor: "green",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "",
            name: "DATA",
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        {
            hid: "GND_middle",
            type: "source",
            x: 0,
            y: 6.1,
            xalign: "start",
            yalign: "start",
            width: 10,
            height: 5,
            borderType: "dotted",
            borderColor: "black",
            borderLineWidth: 0.8,
            borderRadius: "30%",
            postype: "centered",
            position: Position.Left,
            description: "GND",
            name: "GND pin",
            repeated: "yes",
            repeatAtFirst: "no"
        } as HandleDataType,
        ]
    } as ComponentDataType,
}